version: '3.8'

services:
  # Backend API for Production (Render)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crown_security_api_prod
    environment:
      NODE_ENV: production
      PORT: ${PORT:-10000}
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_TTL: ${JWT_ACCESS_TTL:-2592000}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL:-2592000}
      FRONTEND_URL: ${FRONTEND_URL}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      APP_NAME: ${APP_NAME:-Crown Security API}
      APP_VERSION: ${APP_VERSION:-1.0.0}
    ports:
      - "${PORT:-10000}:${PORT:-10000}"
    networks:
      - crown_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${PORT:-10000}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  crown_network:
    driver: bridge
